import { NextResponse } from 'next/server';
import { getSupabaseAdmin } from '@/lib/supabase-server';
import { getRelayParticipant, relayWindow } from '@/lib/trivia-relay';
export const dynamic='force-dynamic';
export async function POST(request:Request){
 const body=await request.json().catch(()=>null);const {eventId,experienceId,deviceToken}=body??{};if(!eventId||!experienceId)return NextResponse.json({error:'Invalid request.'},{status:400});const supabase=getSupabaseAdmin();const participant=await getRelayParticipant(supabase,eventId,experienceId,deviceToken);if(!participant)return NextResponse.json({error:'You are not locked into trivia.'},{status:403});
 const {data:experience}=await supabase.from('experiences').select('id,event_id,config').eq('id',experienceId).maybeSingle();if(!experience||experience.event_id!==eventId)return NextResponse.json({error:'Trivia not found.'},{status:404});let {data:session}=await supabase.from('trivia_relay_sessions').select('*').eq('event_id',eventId).eq('experience_id',experienceId).maybeSingle();if(!session){const made=await supabase.from('trivia_relay_sessions').insert({event_id:eventId,experience_id:experienceId,status:'lobby'}).select('*').single();if(made.error)return NextResponse.json({error:made.error.message},{status:500});session=made.data;}
 const [membersRes,attemptsRes]=await Promise.all([supabase.from('event_participants').select('id,display_name,locked_at').eq('event_id',eventId).eq('experience_id',experienceId).order('locked_at'),supabase.from('trivia_relay_attempts').select('id,participant_id,sender_participant_id,question_id,difficulty,status,is_correct,points_awarded,answered_at,opened_at').eq('session_id',session.id).order('opened_at',{ascending:false})]);const members=membersRes.data??[];const attempts=attemptsRes.data??[];const names=new Map(members.map(m=>[m.id,m.display_name]));const latest=attempts.find(a=>a.status==='answered')??null;const current=members.find(m=>m.id===session.current_participant_id)??null;const sender=members.find(m=>m.id===session.sender_participant_id)??null;const openMine=attempts.find(a=>a.status==='open'&&a.participant_id===participant.id)??null;let openQuestion=null;if(openMine){const {data:q}=await supabase.from('trivia_questions').select('question,answers,category,points').eq('id',openMine.question_id).maybeSingle();if(q)openQuestion={attemptId:openMine.id,...q,difficulty:openMine.difficulty};}
 const stats=members.map(m=>{const mine=attempts.filter(a=>a.participant_id===m.id&&a.status==='answered');return{id:m.id,name:m.display_name,answered:mine.length,correct:mine.filter(a=>a.is_correct).length,hardCorrect:mine.filter(a=>a.is_correct&&a.difficulty==='violence').length,points:mine.reduce((n,a)=>n+(a.points_awarded??0),0)};});const duration=Number((experience.config as any)?.duration_minutes??120);const window=await relayWindow(supabase,session.id,duration);if(window.closed&&session.status==='live'){await supabase.from('trivia_relay_sessions').update({status:'complete'}).eq('id',session.id);session={...session,status:'complete'};}
 return NextResponse.json({participant,session,members,current,sender,openQuestion,latestResult:latest?{participantId:latest.participant_id,name:names.get(latest.participant_id)??'Guest',correct:latest.is_correct,difficulty:latest.difficulty,points:latest.points_awarded}:null,stats,window});
}
