'use client';
import {useCallback,useEffect,useState} from 'react';
import {getSupabaseBrowser} from '@/lib/supabase-browser';
import type {Experience} from '@/lib/types';
type Q={attemptId:string;question:string;answers:string[];category:string;points:number;difficulty:'nice'|'violence'};type M={id:string;display_name:string;locked_at:string};type S={participant:{id:string;display_name:string};session:{id:string;status:'lobby'|'live'|'complete';pending_difficulty:'nice'|'violence'|null};members:M[];current:M|null;sender:M|null;openQuestion:Q|null;latestResult:{name:string;correct:boolean}|null;stats:Array<{id:string;name:string;answered:number;correct:number;hardCorrect:number;points:number}>};
function token(){const k='interactive-event-device-token';let t=localStorage.getItem(k);if(!t){t=crypto.randomUUID();localStorage.setItem(k,t);}return t;}async function post<T>(u:string,b:unknown):Promise<T>{const r=await fetch(u,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(b),cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Something went wrong.');return j as T;}
export default function TriviaRelay({eventId,experience,onBack}:{eventId:string;experience:Experience;onBack:()=>void}){const[state,setState]=useState<S|null>(null),[question,setQuestion]=useState<Q|null>(null),[result,setResult]=useState<{correct:boolean;pointsAwarded:number}|null>(null),[difficulty,setDifficulty]=useState<'nice'|'violence'|null>(null),[nextPlayer,setNextPlayer]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const load=useCallback(async()=>{try{const n=await post<S>('/api/trivia/relay/state',{eventId,experienceId:experience.id,deviceToken:token()});setState(n);if(n.openQuestion&&!question)setQuestion(n.openQuestion);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load trivia.');}},[eventId,experience.id,question]);useEffect(()=>{void load();},[eventId,experience.id]);useEffect(()=>{const t=setInterval(()=>void load(),4000);return()=>clearInterval(t);},[load]);useEffect(()=>{if(!state)return;const s=getSupabaseBrowser();const c=s.channel(`trivia-relay-${state.session.id}`).on('postgres_changes',{event:'*',schema:'public',table:'trivia_relay_sessions',filter:`id=eq.${state.session.id}`},()=>void load()).subscribe();return()=>{void s.removeChannel(c);};},[state?.session.id,load]);async function act(action:string,extra:Record<string,unknown>={}){setBusy(true);setError('');try{const r=await post<any>('/api/trivia/relay/action',{action,eventId,experienceId:experience.id,deviceToken:token(),...extra});if(action==='openQuestion'){setQuestion(r);setResult(null);}if(action==='pass'){setQuestion(null);setResult(null);setDifficulty(null);setNextPlayer('');}await load();}catch(e){setError(e instanceof Error?e.message:'Could not update trivia.');}finally{setBusy(false);}}async function answer(choice:number){if(!question)return;setBusy(true);try{const r=await post<{correct:boolean;pointsAwarded:number}>('/api/trivia/relay/answer',{attemptId:question.attemptId,eventId,experienceId:experience.id,deviceToken:token(),choice});setResult(r);await load();}catch(e){setError(e instanceof Error?e.message:'Could not submit answer.');}finally{setBusy(false);}}
 // Leaving the screen mid-question forfeits it (0 points) and hands the turn to someone else,
 // same rule as the trivia board: it stops the answer being looked up elsewhere.
 useEffect(()=>{
  if(!question||result)return;
  const attemptId=question.attemptId;
  const forfeit=()=>{
   const payload=JSON.stringify({action:'forfeit',eventId,experienceId:experience.id,deviceToken:token(),attemptId});
   navigator.sendBeacon('/api/trivia/relay/action',new Blob([payload],{type:'application/json'}));
   setQuestion(null);
  };
  const onVisibility=()=>{if(document.visibilityState==='hidden')forfeit();};
  document.addEventListener('visibilitychange',onVisibility);
  window.addEventListener('pagehide',forfeit);
  return()=>{document.removeEventListener('visibilitychange',onVisibility);window.removeEventListener('pagehide',forfeit);};
 },[question,result,eventId,experience.id]);
 if(!state)return <section><button className="back" onClick={onBack}>← Back to experiences</button><div className="panel">{error||'Loading trivia…'}</div></section>;if(state.session.status==='lobby')return <section><button className="back" onClick={onBack}>← Back to experiences</button><div className="panel"><div className="category">A Little Challenge</div><p className="prompt">Your trivia crew is forming.</p><div className="crewList">{state.members.map(m=><div className="crewChip" key={m.id}>{m.display_name}</div>)}</div><button className="primary" disabled={busy||state.members.length<2} onClick={()=>act('start')}>Start trivia</button></div></section>;if(state.session.status==='complete')return <section><button className="back" onClick={onBack}>← Back to experiences</button><div className="panel"><div className="category">Trivia complete</div><div className="assignmentList">{[...state.stats].sort((a,b)=>b.points-a.points).map(s=><div className="assignmentCard" key={s.id}><span>{s.name}</span><strong>{s.points} pts</strong><small>{s.correct}/{s.answered} correct · {s.hardCorrect} violence survived</small></div>)}</div></div></section>;
 const mine=state.current?.id===state.participant.id;if(question&&mine)return <section><button className="back" onClick={onBack}>← Leave (forfeits this question)</button><div className="panel"><div className="category">{question.difficulty==='violence'?'Choose Violence':'Play Nice'} · {question.category}</div>{state.sender&&<p className="note">{state.sender.display_name} sent this one to you.</p>}<p className="prompt">{question.question}</p><div className="choices">{question.answers.map((a,i)=><button className="choice" disabled={busy||!!result} onClick={()=>answer(i)} key={i}>{a}</button>)}</div>{result&&<><div className={result.correct?'status resultGood':'status resultBad'}>{result.correct?`Correct. +${result.pointsAwarded}`:'Nope. They got you.'}</div><h3 className="stepTitle">How are you feeling?</h3><div className="triviaMood"><button className={`moodButton ${difficulty==='nice'?'selected':''}`} onClick={()=>setDifficulty('nice')}>Play Nice<span>Send an easier one.</span></button><button className={`moodButton violence ${difficulty==='violence'?'selected':''}`} onClick={()=>setDifficulty('violence')}>Choose Violence<span>Send the hard one.</span></button></div>{difficulty&&<><h3 className="stepTitle">Who gets it?</h3><div className="scenarioChoiceGrid">{state.members.filter(m=>m.id!==state.participant.id).map(m=><button className={`scenarioChoice ${nextPlayer===m.id?'selected':''}`} key={m.id} onClick={()=>setNextPlayer(m.id)}>{m.display_name}</button>)}</div><button className="primary" disabled={!nextPlayer||busy} onClick={()=>act('pass',{difficulty,nextParticipantId:nextPlayer})}>Send {difficulty==='violence'?'the violence':'the nice one'}</button></>}</>}</div></section>;
 if(mine)return <section><button className="back" onClick={onBack}>← Back to experiences</button><div className="panel"><div className="category">You’re up</div><p className="prompt">{state.sender?`${state.sender.display_name} ${state.session.pending_difficulty==='violence'?'chose violence.':'played nice.'}`:'You’re starting us off.'}</p><button className="primary" disabled={busy} onClick={()=>act('openQuestion')}>Show me my question</button>{state.latestResult&&<div className="status">{state.latestResult.name} {state.latestResult.correct?'got the last one right.':'got the last one wrong.'}</div>}</div></section>;
 return <section><button className="back" onClick={onBack}>← Back to experiences</button><div className="panel"><div className="category">Trivia crew</div><p className="prompt">{state.current?.display_name??'Someone'} is answering now.</p>{state.latestResult&&<div className={state.latestResult.correct?'status resultGood':'status resultBad'}>{state.latestResult.name} {state.latestResult.correct?'got it right.':'got it wrong.'}</div>}<div className="assignmentList">{state.stats.map(s=><div className="assignmentCard" key={s.id}><span>{s.name}</span><strong>{s.points}</strong><small>{s.correct}/{s.answered} correct</small></div>)}</div></div></section>;
}
