'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { getSupabaseBrowser } from '@/lib/supabase-browser';
import type { Experience, Prompt } from '@/lib/types';

type TroubleRole={key:string;label:string;bio:string;planning_prompt:string;constraint:string};
type Member={id:string;display_name:string;locked_at:string};
type Assignment={role_key:string;participant_id:string};
type Piece={participant_id:string;role_key:string;contribution:string;approved:boolean};
type TroubleState={participant:{id:string;display_name:string;experience_id:string};session:{id:string;status:'lobby'|'voting'|'planning'|'review'|'submitted';plain_summary:string|null;vote_round:number;report_style?:'news'|'police'|null;report_text?:string|null};prompt:Prompt;roles:TroubleRole[];members:Member[];myVotes:Array<{role_key:string;nominee_participant_id:string}>;assignments:Assignment[];myAssignment:Assignment|null;myRole:TroubleRole|null;myPiece:Piece|null;pieces:Piece[];minCrew:number};

function getDeviceToken(){const key='interactive-event-device-token';let t=window.localStorage.getItem(key);if(!t){t=crypto.randomUUID();window.localStorage.setItem(key,t);}return t;}
async function post<T>(url:string,body:unknown):Promise<T>{const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Something went wrong.');return j as T;}

function SpeechButton({onText}:{onText:(text:string)=>void}){const[listening,setListening]=useState(false);function start(){const w=window as any;const SR=w.SpeechRecognition||w.webkitSpeechRecognition;if(!SR){alert('Voice transcription is not supported in this browser. You can type instead.');return;}const rec=new SR();rec.lang='en-CA';rec.interimResults=false;rec.continuous=false;rec.onstart=()=>setListening(true);rec.onend=()=>setListening(false);rec.onerror=()=>setListening(false);rec.onresult=(e:any)=>{const text=Array.from(e.results).map((x:any)=>x[0]?.transcript??'').join(' ').trim();if(text)onText(text);};rec.start();}return <button type="button" className="secondary" onClick={start}>{listening?'Listening…':'🎙 Speak my part'}</button>}

export default function TroubleCrew({eventId,experience,onBack}:{eventId:string;experience:Experience;onBack:()=>void}){
  const[state,setState]=useState<TroubleState|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[nominations,setNominations]=useState<Record<string,string>>({});const[contribution,setContribution]=useState('');
  const load=useCallback(async()=>{try{const n=await post<TroubleState>('/api/trouble/state',{eventId,experienceId:experience.id,deviceToken:getDeviceToken()});setState(n);setError('');if(n.myPiece?.contribution)setContribution(n.myPiece.contribution);if(n.myVotes?.length)setNominations(Object.fromEntries(n.myVotes.map(v=>[v.role_key,v.nominee_participant_id])));}catch(e){setError(e instanceof Error?e.message:'Could not load Trouble.');}},[eventId,experience.id]);
  useEffect(()=>{void load();},[load]);
  // Realtime keeps the crew in sync; this poll is a safety net if an update is missed.
  useEffect(()=>{const t=window.setInterval(()=>void load(),10000);return()=>window.clearInterval(t);},[load]);
  useEffect(()=>{if(!state)return;const s=getSupabaseBrowser();const c=s.channel(`trouble-${state.session.id}`).on('postgres_changes',{event:'*',schema:'public',table:'event_participants',filter:`event_id=eq.${eventId}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'trouble_sessions',filter:`id=eq.${state.session.id}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'trouble_role_assignments',filter:`session_id=eq.${state.session.id}`},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'trouble_plan_pieces',filter:`session_id=eq.${state.session.id}`},()=>void load()).subscribe();return()=>{void s.removeChannel(c);};},[state?.session.id,eventId,load]);
  async function action(name:string,extra:Record<string,unknown>={}){setBusy(true);setError('');try{await post('/api/trouble/action',{action:name,eventId,experienceId:experience.id,deviceToken:getDeviceToken(),...extra});await load();}catch(e){setError(e instanceof Error?e.message:'Could not update the game.');}finally{setBusy(false);}}
  if(!state)return <section><button className="back" onClick={onBack}>← Back</button><div className="panel">{error?<div className="error">{error}</div>:'Loading crew…'}</div></section>;
  if(state.session.status==='lobby')return <section><div className="panel"><div className="category">A Little Trouble</div><p className="prompt">Your crew is forming.</p><p className="note">Everyone who chose A Little Trouble tonight is on this team. Once the crew is locked, nobody new can join and nobody can switch categories.</p><div className="crewList">{state.members.map(m=><div className="crewChip" key={m.id}>{m.display_name}</div>)}</div><button className="primary" disabled={busy||state.members.length<state.minCrew} onClick={()=>action('lockCrew')}>Everyone&apos;s here — lock the crew</button>{error&&<div className="error">{error}</div>}</div></section>;
  if(state.session.status==='voting'){const complete=state.roles.every(r=>!!nominations[r.key]);return <section><div className="panel"><div className="category">Tonight&apos;s mission</div><p className="prompt">{state.prompt.body}</p>{state.prompt.note&&<p className="note">{state.prompt.note}</p>}<div className="status">First, decide who this crew thinks everybody is.</div>{state.roles.map(role=><div className="roleVoteCard" key={role.key}><h3>{role.label}</h3><p>{role.bio}</p><div className="scenarioChoiceGrid">{state.members.map(m=><button key={m.id} type="button" className={`scenarioChoice ${nominations[role.key]===m.id?'selected':''}`} onClick={()=>setNominations(c=>({...c,[role.key]:m.id}))}>{m.display_name}{m.id===state.participant.id?' (me)':''}</button>)}</div></div>)}<button className="primary" disabled={busy||!complete} onClick={()=>action('voteRoles',{nominations:state.roles.map(r=>({roleKey:r.key,nomineeParticipantId:nominations[r.key]}))})}>Submit my role votes</button><p className="tiny">You can vote for yourself. The server assigns one primary role per person from the whole crew&apos;s votes.</p>{error&&<div className="error">{error}</div>}</div></section>}
  if(state.session.status==='planning'){if(!state.myRole)return <section><div className="panel">Waiting for role assignments…</div></section>;return <section><div className="panel"><div className="category">You are {state.myRole.label}</div><p className="prompt">{state.myRole.planning_prompt}</p><div className="scenarioRule"><strong>Your constraint</strong><span>{state.myRole.constraint}</span></div><textarea className="textArea" maxLength={1800} placeholder="Talk it out, then record your piece here." value={contribution} onChange={e=>setContribution(e.target.value)}/><SpeechButton onText={text=>setContribution(c=>`${c}${c?' ':''}${text}`)}/><button className="primary" disabled={busy||!contribution.trim()} onClick={()=>action('savePiece',{contribution})}>Save my part</button><div className="status">{state.pieces.length} of {state.members.length} crew members have submitted their piece.</div>{error&&<div className="error">{error}</div>}</div></section>}
  if(state.session.status==='review'){const mine=state.pieces.find(p=>p.participant_id===state.participant.id);const approvals=state.pieces.filter(p=>p.approved).length;return <section><div className="panel"><div className="category">Crew review</div><p className="prompt">This is the plain version of the plan. Read it together.</p><pre className="plainPlan">{state.session.plain_summary}</pre><button className="primary" disabled={busy||!!mine?.approved} onClick={()=>action('approve')}>{mine?.approved?'I approved this plan':'I approve the final plan'}</button><div className="status">{approvals} of {state.members.length} approvals in.</div>{error&&<div className="error">{error}</div>}</div></section>}
  const report=state.session.report_text;
  return <section><div className="panel">
    <div className="category">{report?(state.session.report_style==='news'?'Breaking news':'Police incident report'):'Plan submitted'}</div>
    <p className="prompt">{report?'The whole crew approved it. Here is how the story got told.':'The whole crew approved it.'}</p>
    {report?<div className="scenarioSummary crewReport">{report}</div>:<pre className="plainPlan">{state.session.plain_summary}</pre>}
    {report&&<details className="crewPlanDetails"><summary>Show the plain plan</summary><pre className="plainPlan">{state.session.plain_summary}</pre></details>}
    <p className="note">Read it aloud to the table.</p>
  </div></section>;
}
