import { NextResponse } from 'next/server';
import { getSupabaseAdmin } from '@/lib/supabase-server';
import { getRelayParticipant, relayWindow } from '@/lib/trivia-relay';
function one<T>(x:T[]){return x[Math.floor(Math.random()*x.length)];}
export async function POST(request:Request){
 const body=await request.json().catch(()=>null);const {action,eventId,experienceId,deviceToken}=body??{};if(!action||!eventId||!experienceId)return NextResponse.json({error:'Invalid request.'},{status:400});const supabase=getSupabaseAdmin();const participant=await getRelayParticipant(supabase,eventId,experienceId,deviceToken);if(!participant)return NextResponse.json({error:'You are not locked into trivia.'},{status:403});const [{data:experience},{data:session}]=await Promise.all([supabase.from('experiences').select('id,event_id,config').eq('id',experienceId).maybeSingle(),supabase.from('trivia_relay_sessions').select('*').eq('event_id',eventId).eq('experience_id',experienceId).maybeSingle()]);if(!experience||!session)return NextResponse.json({error:'Trivia session not found.'},{status:404});const {data:members}=await supabase.from('event_participants').select('id,display_name,locked_at').eq('event_id',eventId).eq('experience_id',experienceId).order('locked_at');const crew=members??[];
 if(action==='start'){if(session.status!=='lobby')return NextResponse.json({ok:true});if(crew.length<2)return NextResponse.json({error:'Need at least two trivia players.'},{status:400});await supabase.from('trivia_relay_sessions').update({status:'live',current_participant_id:crew[0].id,sender_participant_id:null,pending_difficulty:'nice',round_number:1,started_at:new Date().toISOString()}).eq('id',session.id).eq('status','lobby');return NextResponse.json({ok:true});}
 if(session.status!=='live')return NextResponse.json({error:'Trivia is not live.'},{status:409});const duration=Number((experience.config as any)?.duration_minutes??120);const window=await relayWindow(supabase,session.id,duration);if(window.closed){await supabase.from('trivia_relay_sessions').update({status:'complete'}).eq('id',session.id);return NextResponse.json({error:'Time is up.'},{status:409});}
 if(action==='openQuestion'){if(session.current_participant_id!==participant.id)return NextResponse.json({error:'It is not your turn.'},{status:403});const {data:existing}=await supabase.from('trivia_relay_attempts').select('id').eq('session_id',session.id).eq('participant_id',participant.id).eq('status','open').maybeSingle();if(existing)return NextResponse.json({error:'You already have an open question.'},{status:409});const difficulty=session.pending_difficulty==='violence'?'violence':'nice';const points=difficulty==='violence'?Number((experience.config as any)?.relay_hard_points??5):Number((experience.config as any)?.relay_easy_points??1);const [{data:questions},{data:seen}]=await Promise.all([supabase.from('trivia_questions').select('id,question,answers,category,points').eq('experience_id',experienceId).eq('points',points),supabase.from('trivia_relay_attempts').select('question_id').eq('session_id',session.id)]);const used=new Set((seen??[]).map(x=>x.question_id));let choices=(questions??[]).filter(q=>!used.has(q.id));if(!choices.length)choices=questions??[];const q=one(choices);if(!q)return NextResponse.json({error:`No ${difficulty==='violence'?'hard':'easy'} questions are configured.`},{status:409});const {data:attempt,error}=await supabase.from('trivia_relay_attempts').insert({session_id:session.id,participant_id:participant.id,sender_participant_id:session.sender_participant_id,question_id:q.id,difficulty}).select('id').single();if(error||!attempt)return NextResponse.json({error:'Could not open question.'},{status:500});return NextResponse.json({attemptId:attempt.id,question:q.question,answers:q.answers,category:q.category,points:q.points,difficulty});}
 if(action==='pass'){if(session.current_participant_id!==participant.id)return NextResponse.json({error:'It is not your turn.'},{status:403});const nextParticipantId=String(body.nextParticipantId??'');const difficulty=body.difficulty==='violence'?'violence':'nice';if(nextParticipantId===participant.id)return NextResponse.json({error:'Choose somebody else.'},{status:400});if(!crew.some(m=>m.id===nextParticipantId))return NextResponse.json({error:'That person is not in the trivia crew.'},{status:400});const {data:latest}=await supabase.from('trivia_relay_attempts').select('status').eq('session_id',session.id).eq('participant_id',participant.id).order('opened_at',{ascending:false}).limit(1).maybeSingle();if(!latest||latest.status!=='answered')return NextResponse.json({error:'Answer your question first.'},{status:409});await supabase.from('trivia_relay_sessions').update({current_participant_id:nextParticipantId,sender_participant_id:participant.id,pending_difficulty:difficulty,round_number:(session.round_number??0)+1}).eq('id',session.id);return NextResponse.json({ok:true});}
 if(action==='forfeit'){
  // Leaving the screen mid-question forfeits it at 0 points, same rule as the trivia board:
  // it keeps an answer from being looked up and it stops one absent player from stalling
  // everyone else (only the current player can normally hand off the turn).
  const attemptId=String(body.attemptId??'');
  const {data:attempt}=await supabase.from('trivia_relay_attempts').select('id,participant_id,status').eq('id',attemptId).eq('session_id',session.id).maybeSingle();
  if(!attempt||attempt.participant_id!==participant.id) return NextResponse.json({error:'Question not found.'},{status:404});
  if(attempt.status!=='open') return NextResponse.json({ok:true});
  const {data:closed}=await supabase.from('trivia_relay_attempts').update({status:'answered',is_correct:false,points_awarded:0,answered_at:new Date().toISOString()}).eq('id',attempt.id).eq('status','open').select('id');
  if(!closed?.length) return NextResponse.json({ok:true});
  const others=crew.filter(m=>m.id!==participant.id);
  if(others.length){
    const next=others[Math.floor(Math.random()*others.length)];
    await supabase.from('trivia_relay_sessions').update({current_participant_id:next.id,sender_participant_id:participant.id,pending_difficulty:'nice',round_number:(session.round_number??0)+1}).eq('id',session.id).eq('current_participant_id',participant.id);
  }
  return NextResponse.json({ok:true});
 }
 return NextResponse.json({error:'Unknown action.'},{status:400});
}
